---
title: "Demographics and Descriptives"
output:
  html_document:
    toc: true
    toc_depth: 3
    keep_md: no
    toc_float: true
    code_folding: hide
  word_document:
    keep_md: no
    toc: no
---

<!-- These two chunks should be added in the beginning of every .Rmd that you want to source an .R script -->
<!--  The 1st mandatory chunck  -->
<!--  Set the working directory to the repository's base directory -->
```{r, echo=F, message=F} 
#Don't combine this call with any other chunk 
# cat("Working directory: ", getwd()) # check where you are
  library(knitr)
# Rmd is in "./reports/reportA/reportA.Rmd", but now the root is "./"
  knitr::opts_knit$set(root.dir='../../') 
```

<!--  The 2nd mandatory chunck  -->
<!-- Set the report-wide options, and point to the external code file. -->
```{r set_options, echo=F}
# set options shared by all chunks
opts_chunk$set(
  results='show', 
  message = TRUE,
  comment = NA, 
  tidy = FALSE,
  fig.height = 5, 
  fig.width = 9, 
  out.width = "900px",
  fig.path = 'figure_rmd/',     
  dev = "png",
  dpi = 200
  # fig.path = 'figure_pdf/',     
  # dev = "pdf"#,
  # dev.args=list(pdf = list(colormodel = 'cmyk'))
)
echoChunks <- TRUE
options(width=120) #So the output is 50% wider than the default.
# connect to the file with the underlying R script  
read_chunk("./analysis/1-first-look/1-first-look.R") 
```

## Environment 
This section offers technical detail on the environment and data preparation. Non-technical readers should feel free to skip. 
```{r load-packages, echo=echoChunks, message=FALSE}
```

```{r load-sources, echo=echoChunks, message=FALSE}
```

```{r declare-globals, echo=echoChunks, results='show', message=FALSE}
```

```{r load-data, echo=echoChunks, results='hide', message=FALSE}
```

```{r inspect-data, echo=echoChunks, results='show', message=FALSE}
```

```{r tweak-data, echo=echoChunks, results='show', message=FALSE}
```

```{r add-new-names, echo=echoChunks, results='show', message=FALSE}
```

```{r tweak-data-1, echo=echoChunks, results='show', message=FALSE}
```

# Survey Response
This section demonstrates the attrition of survey responses due to data quality
```{r survey-response, echo=TRUE, results='show', message=FALSE, warning=FALSE}
```

# Demographics
```{r demographics, echo=FALSE, results='show', message=FALSE, warning=FALSE, cache = T}
```

# (Q4) Knowledge of Opioid Use
```{r opioid-use-prep, echo=FALSE, results='show', message=FALSE, out.width ="900px", warning=FALSE, cache = T}
```

```{r opioid-use-1, echo=FALSE, results='show', message=FALSE, out.width ="900px", warning=FALSE, cache = T}
```

```{r opioid-use-2, echo=FALSE, fig.height=10, fig.width=10, message=FALSE, warning=FALSE, cache=T, out.width="1200px", results='show'}
```

```{r opioid-use-3, echo=FALSE, results='asis', message=FALSE, out.width ="900px", warning=FALSE, cache = T}
```

# (Q7) Methodone
```{r methodone-prep, echo=FALSE, results='show', message=FALSE, out.width ="900px", warning=FALSE, cache = T}
```

```{r methodone-1, echo=FALSE, results='show', message=FALSE, out.width ="900px", warning=FALSE, cache = T}
```

```{r methodone-2, echo=FALSE, fig.height=10, fig.width=10, message=FALSE, warning=FALSE, cache=T, out.width="1200px", results='show'}
```

```{r methodone-3, echo=FALSE, results='asis', message=FALSE, out.width ="900px", warning=FALSE, cache = T}
```

# (Q8) Buprenorphine
```{r buprenorphine-prep, echo=FALSE, results='show', message=FALSE, out.width ="900px", warning=FALSE, cache = T}
```

```{r buprenorphine-1, echo=FALSE, results='show', message=FALSE, out.width ="900px", warning=FALSE, cache = T}
```

```{r buprenorphine-2, echo=FALSE, fig.height=10, fig.width=10, message=FALSE, warning=FALSE, cache=T, out.width="1200px", results='show'}
```

```{r buprenorphine-3, echo=FALSE, results='asis', message=FALSE, out.width ="900px", warning=FALSE, cache = T}
```

# Naltrexone
```{r naltrexone-prep, echo=FALSE, results='show', message=FALSE, out.width ="900px", warning=FALSE, cache = T}
```

```{r naltrexone-1, echo=FALSE, results='show', message=FALSE, out.width ="900px", warning=FALSE, cache = T}
```

```{r naltrexone-2, echo=FALSE, fig.height=10, fig.width=10, message=FALSE, warning=FALSE, cache=T, out.width="1200px", results='show'}
```

```{r naltrexone-3, echo=FALSE, results='asis', message=FALSE, out.width ="900px", warning=FALSE, cache = T}
```




